mini_second/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
   # path('', views.index),
   path('', views.PostList.as_view(), name='index'),
   path('createform/', views.createform, name='createform'),
   path('logout/', views.logout, name='logout'),
   path('signin/', views.signin, name='login'),

]

webapp/models.py
from django.db import models


class Info(models.Model):
   FIRMV_2_32 = 'r1m_v2.32'
   FIRMV_CHOICE = (
      (FIRMV_2_32, 'r1m_v2.32'),
   )

   battery = models.CharField(max_length=30)
   color =  models.CharField(max_length=30, default=0)
   runtime = models.CharField(null=True, max_length=30)
   firmV = models.CharField(choices=FIRMV_CHOICE, max_length=20,default=FIRMV_2_32)

   created_at = models.DateTimeField(auto_now=True)

   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
      return f'[{self.pk}] bat : {self.battery}% / runtime : {self.runtime}ms'

webapp/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .models import Info
from django.views.generic import ListView

# Create your views here.

class PostList(ListView):
   model = Info
   ordering = '-pk'
   paginate_by = 1


def createform(request):
   std = Info()
   std.battery = request.GET['battery']
   std.color = request.GET['color']
   std.runtime = request.GET['runtime']
   std.firmV = request.GET['firmV']

   std.save()

   return redirect('/')


def signin(request):
    if request.method == "GET":
        return redirect('webapp:index')

    elif request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('webapp:index')
            else:
                return redirect('webapp:index')



def logout(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect('webapp:index')

webapp/templates/webapp/info_review.html
<section id="about_list" class="about_list">
    <div class="container">
        <div class="section-title">
            <h2>Info</h2>
            <h3>OMO R1MINI <span>데이터 조회</span></h3>
            <p>데이터 정보를 조회할 수 있습니다.</p>
        </div>
        <div class="row content">
          <div class="section-title">

            <!-- Project Card Example -->
            {% if info_list %}
            {% for p in info_list %}
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <div class="infoarea">
                  <h6 class="m-0 font-weight-bold text-primary infoTITLE">INFO</h6>

        {% if is_paginated %}
          <ul class="pagination justify-content-center my-4">
              {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                  <a class="page-link" href="#">&larr; Newer</a>
              </li>
              {% endif %}

              {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Older &rarr;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Older &rarr;</a>
                </li>
              {% endif %}
          </ul>
            {% endif %}
                </div>
              </div>
              <div class="card-body">
                <div class="infoTop">
                  <div class="bat">
                    <h4 class="small font-weight-bold">BATTERY<span class="float-right bat_review">
                        {{ p.battery }}
                      </span></h4>
                    <div class="progress mb-4">
                      <div class="progress bat_prog_review" role="progressbar" aria-label="Animated striped example" aria-valuenow="20"
                        aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bat_prog_col_review" style="width: 100%"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                  <div class="infoBottom">
                    <div class="colInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold color_box_fig">COLOR<span class="float-right">

                        <div>
                          <input class="color_box_input" type="color" value="{{ p.color }}" disabled />
                        </div>
                        </span></h4>
                      </div>
                    </div>
                    <div class="runInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold runtime_fig">RUN TIME<span class="float-right bat-fig">

                      <div>
                        <h3 class="runtime_info">
                          {{ p.runtime }}
                        </h3>
                      </div>

                      </span></h4>
                      </div>
                    </div>
                    <div class="firmV mb-4">
                      <h4 class="small font-weight-bold firmV_fig">firmV<span class="float-right bat-fig">
                      <div>
                        <h3 class="firmV_info">
                          {{ p.firmV }}
                        </h3>
                      </div>
                      </span></h4>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <div class="infoarea">
                  <h6 class="m-0 font-weight-bold text-primary infoTitle">INFO</h6>
                  {% if user.is_authenticated %}
                  <a href="" title="Button push blue/green" class="button btnPush btnBlueGreen" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">INPUT</a>
                  {% endif %}

                </div>
              </div>
              <div class="card-body">
                <div class="infoTop">
                  <div class="bat">
                    <h4 class="small font-weight-bold">BATTERY<span class="float-right bat-fig" >
                        0
                      </span></h4>
                    <div class="progress mb-4">
                      <div class="progress bat-prog" role="progressbar" aria-label="Animated striped example" aria-valuenow="20"
                        aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bat_prog_col" style="width: 100%"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                  <div class="infoBottom">
                    <div class="colInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold color_box_fig">COLOR<span class="float-right">

                        <div>
                          <input class="color_box_input" type="color" value="#000000" disabled />
                        </div>
                        </span></h4>
                      </div>
                    </div>
                    <div class="runInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold runtime_fig">RUN TIME<span class="float-right bat-fig">

                      <div>
                        <h3 class="runtime_info">
                          0
                        </h3>
                      </div>

                      </span></h4>
                      </div>
                    </div>
                    <div class="firmV mb-4">
                      <h4 class="small font-weight-bold firmV_fig">firmV<span class="float-right bat-fig">
                      <div>
                        <h3 >
                          NULL
                        </h3>
                      </div>
                      </span></h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </div>

      </div>
            </section>
<section id="about_list" class="about_list">
    <div class="container">
        <div class="section-title">
            <h2>Info</h2>
            <h3>OMO R1MINI <span>데이터 조회</span></h3>
            <p>데이터 정보를 조회할 수 있습니다.</p>
        </div>
        <div class="row content">
          <div class="section-title">

            <!-- Project Card Example -->
            {% if info_list %}
            {% for p in info_list %}
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <div class="infoarea">
                  <h6 class="m-0 font-weight-bold text-primary infoTITLE">INFO</h6>

        {% if is_paginated %}
          <ul class="pagination justify-content-center my-4">
              {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                  <a class="page-link" href="#">&larr; Newer</a>
              </li>
              {% endif %}

              {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Older &rarr;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Older &rarr;</a>
                </li>
              {% endif %}
          </ul>
            {% endif %}
                </div>
              </div>
              <div class="card-body">
                <div class="infoTop">
                  <div class="bat">
                    <h4 class="small font-weight-bold">BATTERY<span class="float-right bat_review">
                        {{ p.battery }}
                      </span></h4>
                    <div class="progress mb-4">
                      <div class="progress bat_prog_review" role="progressbar" aria-label="Animated striped example" aria-valuenow="20"
                        aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bat_prog_col_review" style="width: 100%"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                  <div class="infoBottom">
                    <div class="colInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold color_box_fig">COLOR<span class="float-right">

                        <div>
                          <input class="color_box_input" type="color" value="{{ p.color }}" disabled />
                        </div>
                        </span></h4>
                      </div>
                    </div>
                    <div class="runInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold runtime_fig">RUN TIME<span class="float-right bat-fig">

                      <div>
                        <h3 class="runtime_info">
                          {{ p.runtime }}
                        </h3>
                      </div>

                      </span></h4>
                      </div>
                    </div>
                    <div class="firmV mb-4">
                      <h4 class="small font-weight-bold firmV_fig">firmV<span class="float-right bat-fig">
                      <div>
                        <h3 class="firmV_info">
                          {{ p.firmV }}
                        </h3>
                      </div>
                      </span></h4>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <div class="infoarea">
                  <h6 class="m-0 font-weight-bold text-primary infoTitle">INFO</h6>
                  {% if user.is_authenticated %}
                  <a href="" title="Button push blue/green" class="button btnPush btnBlueGreen" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">INPUT</a>
                  {% endif %}

                </div>
              </div>
              <div class="card-body">
                <div class="infoTop">
                  <div class="bat">
                    <h4 class="small font-weight-bold">BATTERY<span class="float-right bat-fig" >
                        0
                      </span></h4>
                    <div class="progress mb-4">
                      <div class="progress bat-prog" role="progressbar" aria-label="Animated striped example" aria-valuenow="20"
                        aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bat_prog_col" style="width: 100%"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                  <div class="infoBottom">
                    <div class="colInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold color_box_fig">COLOR<span class="float-right">

                        <div>
                          <input class="color_box_input" type="color" value="#000000" disabled />
                        </div>
                        </span></h4>
                      </div>
                    </div>
                    <div class="runInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold runtime_fig">RUN TIME<span class="float-right bat-fig">

                      <div>
                        <h3 class="runtime_info">
                          0
                        </h3>
                      </div>

                      </span></h4>
                      </div>
                    </div>
                    <div class="firmV mb-4">
                      <h4 class="small font-weight-bold firmV_fig">firmV<span class="float-right bat-fig">
                      <div>
                        <h3 >
                          NULL
                        </h3>
                      </div>
                      </span></h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </div>

      </div>
            </section>

webapp/templates/webapp/login_temp.html
<!-- Login modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Log In</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body logmodalbody"> <div>
                {% load static %}
                <div class="signin_temp">
                    <div class="signin_form">
                        <div class="signin_img_box">
                            <img class="signin_img" src="{% static 'webapp/assets/img/login.jpg' %}">
                        </div>
                        <form action="{% url 'webapp:login' %}" method="post" class="login_form">{% csrf_token %}
                            <div class="signin_input">
                                <div class="signin_username">
                                    <div class="signin_username_con">
                                        <span class="signin_icon"><i class="fa-regular fa-user"></i></span>
                                        <input type="input" name="username" placeholder="UserName" class="username_input">
                                    </div>
                                </div>
                                <div class="signin_passward">
                                    <div class="signin_passward_con">
                                        <span class="signin_icon"><i class="fa-solid fa-lock"></i></span>
                                        <input type="password" name="password" placeholder="PassWord" class="passward_input">
                                    </div>
                                </div>
                            </div>
                            <div class="signin_btn">
                                <input type="submit" value="Login" class="signin_btn1">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

webapp/templates/webapp/logout_temp.html
        <!-- Logout modal -->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="logoutModalLabel">Log Out</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="logoutmodalbody">
                      <div class="logout_temp"></div>
                      <div id="logout_tdiv"><h3 id="logout_text">로그아웃 되었습니다.</h3></div>
                    </div>
                    <div class="modal-footer">
                        <form action="{% url 'webapp:logout' %}" method="post" class="col-md-4 logout_button">
                          {% csrf_token %}
                          <input type="submit" value="확인">
                        </form>
                    </div>
                </div>
            </div>
        </div>

webapp/templates/webapp/omo_edit.html
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">정보 입력</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'webapp:createform' %}" class="robot_input">
            <div class="modalForm">
              <div>
                <div>
                  배터리<input type="text" name="battery" id="batteryInput">
                </div>
                <br>
                <div>
                  경과 시간<input type="text" name="runtime" id="runtimeInput">
                </div>
                <br>
                <div>
                  색상<input type="color" name="color" id="colorInput">
                </div>
                <br>
                <div>
                  펌웨어 버전
                  <select name="firmV">
                    <option>r1m_v2.32</option>
                  </select>
                </div>
              </div>

              <div class="buttonArea">
                <div>
                  <button type="submit" class="btn btn-secondary">입력</button>
                </div>
                <div class="inputButton">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                </div>
              </div>
            </div>
          </form>

        </div>

      </div>
    </div>
  </div>